# Generated by Django 3.1.4 on 2020-12-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('select_area', models.CharField(max_length=100)),
                ('class_other', models.CharField(max_length=100)),
                ('medium', models.CharField(choices=[('En', 'English'), ('Bn', 'Bangla'), ('Ar', 'Arabic'), ('Ot', 'Other')], default='Bn', max_length=2)),
                ('subjects', models.CharField(max_length=250)),
                ('school_college', models.CharField(max_length=500)),
                ('detail_tuition', models.TextField()),
                ('day_per_week', models.CharField(choices=[('01', '1 day/week'), ('02', '2 day/week'), ('03', '3 day/week'), ('04', '4 day/week'), ('05', '5 day/week'), ('06', '6 day/week'), ('07', '7 day/week')], default='03', max_length=2)),
                ('salary', models.CharField(max_length=50)),
                ('desire_tutor_gender', models.CharField(choices=[('g1', 'Male'), ('g2', 'Female'), ('g3', 'Other')], default='g3', max_length=2)),
                ('address', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
