# Generated by Django 3.1.4 on 2020-12-06 04:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionpost',
            name='preference_tuition_style',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('online', 'Online'), ('private', 'Private'), ('coaching', 'Coaching'), ('group', 'Group')], default='private', max_length=50),
        ),
    ]
