# Generated by Django 3.1.4 on 2020-12-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0002_tuitionpost_preference_tuition_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tuitionpost',
            name='preference_tuition_style',
            field=models.CharField(choices=[('online', 'Online'), ('private', 'Private'), ('coaching', 'Coaching'), ('group', 'Group')], default='private', max_length=10),
        ),
    ]
