# Generated by Django 3.1.4 on 2020-12-06 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0003_auto_20201206_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='tuitionpost',
            name='preference_tuition_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.style'),
        ),
        migrations.AlterField(
            model_name='tuitionpost',
            name='day_per_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.perday'),
        ),
        migrations.AlterField(
            model_name='tuitionpost',
            name='desire_tutor_gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.gender'),
        ),
        migrations.AlterField(
            model_name='tuitionpost',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.district'),
        ),
        migrations.AlterField(
            model_name='tuitionpost',
            name='medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.medium'),
        ),
        migrations.AlterField(
            model_name='tuitionpost',
            name='select_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.area'),
        ),
    ]
