# Generated by Django 3.1.4 on 2020-12-07 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0004_auto_20201206_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuitionpost',
            name='select_area',
        ),
        migrations.AddField(
            model_name='area',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tuition.district'),
        ),
        migrations.AddField(
            model_name='tuitionpost',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuition.area'),
        ),
        migrations.AlterField(
            model_name='tuitionpost',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuition.district'),
        ),
    ]
